// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chong Kae Herng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Global layout */}
        <div className="flex flex-col min-h-screen bg-gray-50 bg-no-repeat bg-center bg-cover"
        style={{ backgroundImage: "url('/asset/BackgroundMain.jpg')" }}
        >
          {/* Navbar always on top */}
          <Navbar />

          {/* Main Content Section (Sidebar lives inside this) */}
          <main className="flex flex-1 p-4 gap-4 relative">
            {/* Sidebar on the left, inside main */}
            <Sidebar />

            {/* Page content */}
            <div className="flex-1 bg-white/50 rounded-3xl shadow-sm p-2 transition-all duration-300 max-w-full">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}


{/* <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <div className="layout-container">
      <Navbar />
      <main className="main-content">
        <Sidebar />
        <div className="page-content">{children}</div>
      </main>
    </div>
  </body>
</html> */}
